version: "3.9"

networks:
    horizon-network:
        name: horizon-network
        driver: bridge
        ipam:
            config:
                -   subnet: 170.18.0.0/16
                    gateway: 170.18.0.1

services:

    horizon-first-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: first-app
        working_dir: /var/www/html/laravel
        stdin_open: true
        tty: true
        ports:
            - 8021:8000
        volumes:
            - ./../composer.json:/var/www/html/laravel/composer.json
            - ./../composer.lock:/var/www/html/laravel/composer.lock
            - ./../app:/var/www/html/laravel/app
            - ./../config:/var/www/html/laravel/config
            - ./../resources/views/email:/var/www/html/laravel/resources/views/email
            - ./../routes:/var/www/html/laravel/routes
            - ./../.env.app1:/var/www/html/laravel/.env
            - ./../vendor:/var/www/html/laravel/vendor                
        # environment:
        #     APP_NAME: FIRST APPLICATION
        #     REDIS_HOST: 170.18.0.1
        #     REDIS_PORT: 6380
        #     QUEUE_CONNECTION: redis
        #     MAIL_MAILER: smtp
        #     MAIL_HOST: 170.18.0.1
        #     MAIL_PORT: 1025
        #     MAIL_USERNAME: ''
        #     MAIL_PASSWORD: ''
        #     MAIL_ENCRYPTION: null   
        #     DEFAULT_QUEUE_NAME: first_app_queue
        networks:
            - horizon-network

    horizon-second-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: second-app
        working_dir: /var/www/html/laravel
        stdin_open: true
        tty: true
        ports:
            - 8022:8000
        volumes:
            - ./../composer.json:/var/www/html/laravel/composer.json       
            - ./../app:/var/www/html/laravel/app
            - ./../resources/views/email:/var/www/html/laravel/resources/views/email
            - ./../routes:/var/www/html/laravel/routes         
            - ./../.env.app2:/var/www/html/laravel/.env       
            - ./../vendor:/var/www/html/laravel/vendor             
        # environment:
        #     APP_NAME: SECOND APPLICATION
        #     REDIS_HOST: 170.18.0.1
        #     REDIS_PORT: 6380
        #     QUEUE_CONNECTION: redis
        #     MAIL_MAILER: smtp
        #     MAIL_HOST: 170.18.0.1
        #     MAIL_PORT: 1025
        #     MAIL_USERNAME: ''
        #     MAIL_PASSWORD: ''
        #     MAIL_ENCRYPTION: null   
        #     DEFAULT_QUEUE_NAME: second_app_queue
        networks:
            - horizon-network

    horizon-third-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: third-app
        working_dir: /var/www/html/laravel
        stdin_open: true
        tty: true
        ports:
            - 8023:8000
        volumes:
            - ./../composer.json:/var/www/html/laravel/composer.json
            - ./../app:/var/www/html/laravel/app
            - ./../resources/views/email:/var/www/html/laravel/resources/views/email
            - ./../routes:/var/www/html/laravel/routes  
            - ./../.env.app3:/var/www/html/laravel/.env  
            - ./../vendor:/var/www/html/laravel/vendor                              
        # environment:
        #     APP_NAME: THIRD APPLICATION
        #     REDIS_HOST: 170.18.0.1
        #     REDIS_PORT: 6380
        #     QUEUE_CONNECTION: redis
        #     MAIL_MAILER: smtp
        #     MAIL_HOST: 170.18.0.1
        #     MAIL_PORT: 1025
        #     MAIL_USERNAME: ''
        #     MAIL_PASSWORD: ''
        #     MAIL_ENCRYPTION: null
        #     DEFAULT_QUEUE_NAME: third_app_queue
        networks:
            - horizon-network

    horizon-redis-server:
        image: redis:7-alpine
        container_name: horizon-redis-server
        restart: always
        ports:
            - "6380:6379"
        command: redis-server --save 20 1 --loglevel warning
        networks:
            - horizon-network

    horizon-php:
        build:
            args:
                user: horizon
                uid: 1000
            context: ./images/php
            dockerfile: Dockerfile
        image: horizon-php81
        container_name: horizon-php
        restart: unless-stopped
        working_dir: /application
        tty: true
        volumes:
            - ./../:/application
            - ./images/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - horizon-network

    horizon-webserver:
        image: nginx:1.25-alpine
        container_name: horizon-webserver
        build:
            context: .
            dockerfile: HorizonDockerfile
        working_dir: /var/www/html/application
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            - ./../:/var/www/html/application
            - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./images/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "8020:8000"
        environment:
            APP_NAME: MAIN APPLICATION
            REDIS_CLIENT: predis        
            DB_HOST: 170.18.0.1
            REDIS_HOST: 170.18.0.1
            REDIS_PORT: 6380
            QUEUE_CONNECTION: redis
            MAIL_MAILER: smtp
            MAIL_HOST: 170.18.0.1
            MAIL_PORT: 1025
            MAIL_USERNAME: ''
            MAIL_PASSWORD: ''
            MAIL_ENCRYPTION: null
            DEFAULT_QUEUE_NAME: main_app_queue   
        depends_on:
            - horizon-redis-server
        networks:
            - horizon-network

    horizon-queue-worker:
        container_name: horizon-worker
        build:
            context: .
            dockerfile: HorizonDockerfile
        working_dir: /application
        command: 'php artisan horizon'
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            - ./../:/application
        environment:
            REDIS_HOST: 170.18.0.1
            REDIS_PORT: 6380
            MAIL_MAILER: smtp
            MAIL_HOST: 170.18.0.1
            MAIL_PORT: 1025
            MAIL_USERNAME: ''
            MAIL_PASSWORD: ''
            MAIL_ENCRYPTION: null
        networks:
            - horizon-network

    horizon-mailhog:
        container_name: horizon-mailhog
        image: mailhog/mailhog:latest
        tty: true
        stdin_open: true
        restart: unless-stopped
        ports:
            - 8025:8025            
            - 1025:1025
        networks:
            - horizon-network            